<?php

namespace Inflections\En;

/**
 * English Uninflectables
 *   See https://en.wikipedia.org/wiki/English_plurals
 *   See https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php.
 */
class Uninflected
{
    public static $version = 1;

    public static $uninflected = [
        'Amoyese' => true,
        'bison' => true,
        'Borghese' => true,
        'bream' => true,
        'breeches' => true,
        'britches' => true,
        'buffalo' => true,
        'cantus' => true,
        'carp' => true,
        'chassis' => true,
        'clippers' => true,
        'cod' => true,
        'coitus' => true,
        'Congoese' => true,
        'contretemps' => true,
        'deer' => true,
        'corps' => true,
        'debris' => true,
        'diabetes' => true,
        'djinn' => true,
        'eland' => true,
        'elk' => true,
        'equipment' => true,
        'Faroese' => true,
        'fish' => true,
        'flounder' => true,
        'Foochowese' => true,
        'gallows' => true,
        'Genevese' => true,
        'Genoese' => true,
        'Gilbertese' => true,
        'graffiti' => true,
        'headquarters' => true,
        'herpes' => true,
        'hijinks' => true,
        'Hottentotese' => true,
        'information' => true,
        'innings' => true,
        'jackanapes' => true,
        'jeans' => true,
        'Kiplingese' => true,
        'Kongoese' => true,
        'Lucchese' => true,
        'mackerel' => true,
        'Maltese' => true,
        'mews' => true,
        'moose' => true,
        'mumps' => true,
        'Nankingese' => true,
        'news' => true,
        'nexus' => true,
        'Niasese' => true,
        'Pekingese' => true,
        'Piedmontese' => true,
        'pike' => true,
        'pincers' => true,
        'Pistoiese' => true,
        'pliers' => true,
        'police' => true,
        'Portuguese' => true,
        'proceedings' => true,
        'rabies' => true,
        'rice' => true,
        'rhinoceros' => true,
        'salmon' => true,
        'samurai' => true,
        'Sarawakese' => true,
        'scissors' => true,
        'series' => true,
        'Shavese' => true,
        'shears' => true,
        'sheep' => true,
        'siemens' => true,
        'species' => true,
        'staff' => true,
        'squid' => true,
        'swine' => true,
        'trousers' => true,
        'trout' => true,
        'tuna' => true,
        'Vermontese' => true,
        'Wenchowese' => true,
        'whiting' => true,
        'wildebeest' => true,
        'Yengeese', ];

    public static $rules = [
        '.*?media',
        'sea[- ]bass',
    ];
}
